Study equality
equinor/sepes-api pull request #114
Opened 2019-11-14 08:46 UTC by Kris2ffer

Added equals method for all internal models.
Input models are meant to be converted before testing equality.

2019-11-14 13:27 UTC, gjersvik requested changes
Some issues with hashes.

2019-11-14 13:27 UTC, gjersvik commented on RestApi/Sepes.RestApi/Model/Pod.cs
> +            hash.Add(users);
You can't simply take the hash of lists. As that link to standard list equality. Best to not use them as part of the hash.

2019-11-14 13:27 UTC, gjersvik commented on RestApi/Sepes.RestApi/Model/Pod.cs
> +            hash.Add(loaded);
Do not put thing in the hash that is not in Equals. The other way around is fine. The hash rule is: If hash != hash then object must be not equal object. If hash == hash then object may be equal object.

2019-11-14 13:27 UTC, gjersvik commented on RestApi/Sepes.RestApi/Model/Study.cs
> +            return HashCode.Combine(studyName, studyId, pods, sponsors, suppliers, archived, userIds, datasetIds);
Cant use pods, sponsors, suppliers, userIds or datasetIds as part of hash. See previous issue.

2019-11-14 13:27 UTC, gjersvik commented on RestApi/Sepes.RestApi.Tests/Model/StudyTest.cs
> +        }
Please split up into multiple tests. This one is to big by an order of magnitude for an Equals test. There should be 3 lines in each. Create a, Create b and compare.

2019-11-15 11:58 UTC, Unicus-Tom approved these changes

2019-11-18 10:05 UTC, gjersvik approved these changes
Looks a lot better.

2019-11-18 15:14 UTC, merged