Frontend scaffolding
equinor/sepes-api pull request #29
Opened 2019-07-10 13:09 UTC by Kris2ffer

2019-07-11 06:03 UTC, gjersvik requested changes

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/package.json
> +  "name": "msal-react",
Should not this be "sepes-frontend" or something like that?

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/public/index.html
> +    <title>React App</title>
Please call the app Sepes Data Sandbox or something similar.

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/public/manifest.json
> +  "name": "Create React App Sample",
Update short name and name to be Sepes related. Sepes and Sepes Data Sandbox for example.

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/src/App.css
> +.App {
No rules from this css file is used. As far as i can see.
Remove or make empty or add some nice Sepes login logout buttons and text.

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/src/App.js
> +  document.getElementById("tokenName").innerText = msalApp.getAccount().name;
This is a super no-no for React. React uses av Virtual DOM so it only updates the Browser DOM when the new version if different than the old one and then only the parts that changes. If you updates the Browser DOM underneath React you will be fighting it every step of the way. And super wired bugs will emerge.

You most likely wants want reacts call a Stateful Component.

2019-07-11 06:03 UTC, gjersvik commented on FrontEnd/src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">
Cant see that this file is used.

2019-07-12 07:39 UTC, Unicus-Tom approved these changes

2019-07-12 07:46 UTC, gjersvik approved these changes
All my concerns was addressed found only a small typo.

2019-07-12 07:46 UTC, gjersvik commented on FrontEnd/public/manifest.json
> +  "name": "CSepes Data Sandbox",
Just a small typo.

2019-07-12 08:06 UTC, merged