Backend securitygroups
equinor/sepes-api pull request #97
Opened 2019-10-30 14:49 UTC by Unicus-Tom

I feel its a bit sloppy but unsure how to make it cleaner. Suggestions welcome in code review.

2019-10-31 12:54 UTC, gjersvik requested changes
PodController and IPodService should be cleaned the rest are just hints and tips.

2019-10-31 12:54 UTC, gjersvik commented on RestApi/Sepes.RestApi/Controllers/PodController.cs
> +        }
Lets keep it out off the controller. If you want to test something you can create a DevController where you add temp and play-around APIes.

2019-10-31 12:54 UTC, gjersvik commented on RestApi/Sepes.RestApi/Services/IAzureService.cs
> +        Task NsgAllowPort(string securityGroupName, string resourceGroupName, string ruleName, int priority, string[] internalAddresses, int internalPort, string[] externalAddresses, int externalPort
Just a Note: Only put stuff in interface that will be used by the pod service.
This Interface looks a bit intimidating. Just a note don't need to fix now.

2019-10-31 12:54 UTC, gjersvik commented on RestApi/Sepes.RestApi/Services/PodService.cs
> +        Task createNsg(string securityGroupName, string resourceGroupName);
At least remove from interface for now.

2019-11-01 13:34 UTC, gjersvik approved these changes

2019-11-01 15:41 UTC, Kris2ffer approved these changes

2019-11-04 09:25 UTC, merged